# Generated by Django 5.2.6 on 2025-10-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('doi', models.CharField(max_length=100, unique=True, verbose_name='DOI')),
                ('mag', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='MircoSoftAD')),
                ('pubmed', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PubMedId')),
                ('issn', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ISSN')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ISBN')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Аннотация')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'Artical',
            },
        ),
        migrations.CreateModel(
            name='ArticalCiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(blank=True, null=True)),
                ('reference_count', models.IntegerField(max_length=100, verbose_name='Цитирований')),
                ('reference_by_count', models.IntegerField(max_length=1000000, verbose_name='Сколько цитировалась')),
                ('source', models.CharField(max_length=20, null=True, verbose_name='Источник')),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Информация о цитировании статьи',
                'verbose_name_plural': 'Информация о цитировании статей',
                'db_table': 'ArticalCiteData',
            },
        ),
        migrations.CreateModel(
            name='ArticalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_artical', models.DateField(verbose_name='Дата написания')),
                ('date_of_last_update', models.DateField(auto_now=True, verbose_name='Последняя дата обновления')),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Информация о дате статьи',
                'verbose_name_plural': 'Информация о датах статьи',
                'db_table': 'ArticalDate',
            },
        ),
    ]
