# Generated by Django 5.2.6 on 2025-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_by_count',
            field=models.IntegerField(verbose_name='Сколько цитировалась'),
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_count',
            field=models.IntegerField(verbose_name='Цитирований'),
        ),
    ]
