# Generated by Django 5.2.6 on 2025-10-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articalcitedata_reference_by_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articalcitedata',
            name='artical',
        ),
        migrations.RemoveField(
            model_name='articaldate',
            name='artical',
        ),
        migrations.AddField(
            model_name='artical',
            name='articalcite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articalcitedata', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='artical',
            name='articaldate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.articaldate', verbose_name='Статья'),
        ),
    ]
