# Generated by Django 5.2.6 on 2025-10-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_articalcitedata_artical_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='articalcite',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='articaldate',
        ),
        migrations.AddField(
            model_name='articalcitedata',
            name='artical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articaldate',
            name='artical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_by_count',
            field=models.IntegerField(verbose_name='Цитирований'),
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_count',
            field=models.IntegerField(verbose_name='Сколько цитировалась'),
        ),
    ]
