# Generated by Django 5.2.6 on 2025-10-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_artical_articalcite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_by_count',
            field=models.IntegerField(verbose_name='Сколько цитировалась'),
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_count',
            field=models.IntegerField(verbose_name='Цитирований'),
        ),
        migrations.CreateModel(
            name='ArticalCiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=100, verbose_name='Имя журнала')),
                ('pages', models.CharField(max_length=30, verbose_name='Страницы')),
                ('volume', models.CharField(max_length=20, verbose_name='Том')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('issue', models.CharField(max_length=20, verbose_name='Проблема')),
                ('artical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Информация для цитирования статьи',
                'verbose_name_plural': 'Информация для цитирования статьи',
                'db_table': 'ArticalCiteInformation',
            },
        ),
    ]
