# Generated by Django 5.2.6 on 2025-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_artical_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articaldate',
            name='date_of_last_update',
            field=models.DateField(auto_now_add=True, verbose_name='Последняя дата обновления'),
        ),
    ]
