# Generated by Django 5.2.6 on 2025-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_articaldate_date_of_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articaldate',
            name='date_of_last_update',
            field=models.DateField(auto_now=True, verbose_name='Последняя дата обновления'),
        ),
    ]
