# Generated by Django 5.2.6 on 2025-10-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_articaldate_date_of_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalciteinformation',
            name='issue',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='articalciteinformation',
            name='pages',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страницы'),
        ),
        migrations.AlterField(
            model_name='articalciteinformation',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Том'),
        ),
    ]
