# Generated by Django 5.2.6 on 2026-01-13 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_articalciteinformation_issue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articalcitedata',
            old_name='reference_by_count',
            new_name='reference_in_work',
        ),
        migrations.RemoveField(
            model_name='articalcitedata',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='articalcitedata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='articalciteinformation',
            name='author',
        ),
        migrations.AddField(
            model_name='artical',
            name='source',
            field=models.CharField(max_length=20, null=True, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='articaldate',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artical',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISSN'),
        ),
    ]
