# Generated by Django 5.2.6 on 2026-01-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_reference_by_count_articalcitedata_reference_in_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articalcitedata',
            options={'verbose_name': 'Информация о цитировании статьи', 'verbose_name_plural': 'Информация о цитированиях статей'},
        ),
        migrations.RenameField(
            model_name='articalcitedata',
            old_name='artical',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articalciteinformation',
            old_name='artical',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articaldate',
            old_name='artical',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='reference_in_work',
            field=models.IntegerField(verbose_name='Источников в статье'),
        ),
        migrations.AlterField(
            model_name='articalciteinformation',
            name='journal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя журнала'),
        ),
        migrations.CreateModel(
            name='ArticleCitePerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('citiation', models.IntegerField(verbose_name='Цитирований за год')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Информация о цитировании за год',
                'verbose_name_plural': 'Информация о цитированиях статей за года',
                'db_table': 'ArticleCitePerYear',
            },
        ),
        migrations.CreateModel(
            name='ArticleMainAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_initials', models.CharField(max_length=100, null=True, verbose_name='Инициалы основного автора')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Инициалы основного автора',
                'verbose_name_plural': 'Инициалы основных авторов',
                'db_table': 'ArticleMainAuthor',
            },
        ),
        migrations.CreateModel(
            name='ArticleOtherAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_initials', models.CharField(max_length=100, null=True, verbose_name='Инициалы дополнительного автора')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Инициалы дополнительно автора',
                'verbose_name_plural': 'Инициалы дополнительных авторов',
                'db_table': 'ArticleOtherAuthor',
            },
        ),
    ]
