# Generated by Django 5.2.6 on 2026-01-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_articalcitedata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='mag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='MircoSoftAG'),
        ),
        migrations.AlterField(
            model_name='articalcitedata',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articalciteinformation',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articaldate',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlemainauthor',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
    ]
