# Generated by Django 5.2.6 on 2026-01-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_artical_mag_alter_articalcitedata_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalcitedata',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articalciteinformation',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articaldate',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlemainauthor',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
    ]
