# Generated by Django 5.2.6 on 2026-01-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_articalcitedata_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articalciteinformation',
            name='journal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя журнала'),
        ),
    ]
