# Generated by Django 5.2.6 on 2026-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_articalciteinformation_journal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
