# Generated by Django 5.2.6 on 2026-01-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_artical_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='pubmed',
            new_name='pmid',
        ),
    ]
