# Generated by Django 5.2.6 on 2026-03-12 16:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_enable_pg_trigram'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artical',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='articlemainauthor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['main_initials'], name='main_initials_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
