# Generated by Django 5.2.6 on 2026-03-15 14:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_enable_pg_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_text', models.TextField(null=True, verbose_name='Аннотация')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Вектор поиска')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='main.artical', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Аннотация',
                'verbose_name_plural': 'Аннотации',
                'db_table': 'ArticalEmbedding',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ArticalEmbe_search__947749_gin')],
            },
        ),
    ]
