# Generated by Django 5.2.6 on 2026-03-24 13:37

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_articalembedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articalembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='vector_cosin', opclasses=['vector_cosine_ops']),
        ),
    ]
