# Generated by Django 5.2.6 on 2026-07-01 10:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_articalembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSearchVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='Вектор поиска')),
            ],
            options={
                'verbose_name': 'Вектор поиска',
                'verbose_name_plural': 'Вектора поиска',
                'db_table': 'ArticleSearchVector',
            },
        ),
        migrations.RemoveIndex(
            model_name='articalembedding',
            name='ArticalEmbe_search__947749_gin',
        ),
        migrations.RemoveField(
            model_name='articalembedding',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='articlesearchvector',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artical', verbose_name='Статья'),
        ),
        migrations.AddIndex(
            model_name='articlesearchvector',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ArticleSear_search__142bf0_gin'),
        ),
    ]
